### PR TITLE
Dereference URI of a statement, requesting turtle

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by anarchivist** [comment]
Initially, I think this is looking good. I'm realizing we didn't talk about the review and merge process when we had our call yesterday! How would you prefer to proceed?

**Comment by literarymachine** [comment]
>  I'm realizing we didn't talk about the review and merge process when we had our call yesterday! How would you prefer to proceed?

I'd propose that @acka47 does the initial review and when he gives his OK I merge, perhaps into an integration branch. Once there is a bigger picture in that integration branch to look at, we'd ping you. This way you wouldn't have to bother about rather smallish changes but would still have the authority of approving merges into the master branch. We could align those reviews with the biweekly development checkins.

**Comment by anarchivist** [comment]
@literarymachine Sounds like a plan. Thanks! :+1:

**Comment by anarchivist** [comment]
For what it's worth, at DPLA we use a slightly lighterweight version of [`git-flow`](http://nvie.com/posts/a-successful-git-branching-model/) for this, where `develop` acts as the integration branch. I defer to you and @acka47 about the specific mechanics, however. :)

**Comment by literarymachine** [comment]
As discussed in https://github.com/rightsstatements/rights-app/pull/18#issuecomment-157775414, pull requests for individual issues will go against the `develop` branch.

**Pull request closed without merging**
