### PR TITLE
Migrate CI/release builds to GitHub Actions

### PR DESCRIPTION
**Pull request by anarchivist**
After our discussion earlier this week and Travis's change in pricing, this migrates our CI and release builds to GitHub Actions.

* Add CI build workflow using Github Actions
* Add release build workflow on tags of format "v*"
* Delete Travis configuration

### CODE REVIEW

**Comment by aisaac** [comment]
Wow this was really quick @anarchivist !
I'm sorry I won't be able to help much with the reviewing. I really know near to nothing about CI. I could try to test the outcome, but that would require me to (1) install and get familiar with stuff I've never done or done a long time ago (2) ask you a lot of things, so maybe it's better if I wait and see what the others say...

**Comment by anarchivist** [comment]
@aisaac: There's nothing to install for this - just FYI. 

As @literarymachine talked about in our call last week, we were using Travis for continuous integration. This had two major uses: 1) running automated tests for pushes/pull requests, and 2) for tagging releases.

The changes in this pull request now use [GitHub Actions](https://github.com/features/actions) to do the same things. So, as you can see on this pull request, this has been run on GitHub Actions for this pull request.

Screen Shot 2020-11-16 at 2 11 51 PM

If you click the [Details](https://github.com/rightsstatements/rights-app/pull/90/checks?check_run_id=1399458276) link, you'll see the results - the tests were run and they pass.

For releases, a version needs to be tagged (e.g. `git tag v1.2.7; git push origin v1.2.7`); once the tag is pushed to GitHub, then GitHub actions will build the release.

**Review by literarymachine — COMMENTED** [review]
I see that a GitHub action is triggered, and I also got an email notification that https://github.com/rightsstatements/rights-app/releases/tag/v8 was released. Alas, I get a 404 for that page and no new release shows up on https://github.com/rightsstatements/rights-app/releases/. Am I missing something, or is there perhaps something wrong with the "Upload Release Asset" step?

**Comment by anarchivist** [comment]
@literarymachine I tagged `v8` as a test release and deleted it, so the error is on my part. I'll tag a new release now as `v1.2.7`.

**Review by literarymachine — APPROVED** [review]
+1, looks good to me

**Comment by aisaac** [comment]
@anarchivist ok thx I thought that the idea was to do a full test, i.e. install the release... So this it good to go indeed!

**Comment by mraadgev** [comment]
Sorry all, I've been sick for the last two weeks so only just saw this process.

------------------

**Pull request merged**
