### PR TITLE
Implement individual statement page structure

### PR DESCRIPTION
**Pull request by literarymachine**
On dev. As can bee seen e.g. in [InC-EDU](http://h2481931.stratoserver.net:9001/page/InC-EDU/1.0/?language=en), the [data](https://github.com/rightsstatements/data-model/blob/master/rights-statements.ttl#L124) currently contains what is separated into a heading and a sub heading in the design as a single string.

### CODE REVIEW

**Comment by anarchivist** [comment]
Is this ready to merge? I notice the colors are different but I imagine more work is coming.

**Comment by literarymachine** [comment]
> Is this ready to merge? I notice the colors are different but I imagine more work is coming.

Please leave PR open, the scope is broader than the title implies and includes implementing the styles, too. Will assign to @anarchivist when ready to merge.

**Comment by literarymachine** [comment]
Tagged as [v0.3.0](https://github.com/rightsstatements/rights-app/releases/tag/v0.3.0) and deployed to staging. See e.g. http://rights-stg.rightsstatements.org/page/1.0/.

**Comment by literarymachine** [comment]
Deployed to dev, see e.g. http://h2481931.stratoserver.net:9001/page/InC/1.0/?language=en

**Comment by anarchivist** [comment]
I think we'll need another tag because of the most recent two commits, but this is good to go.

**Pull request merged**
